export const nelloreVillagesByMandal: {
  [mandal: string]: string[];
} = {
  "Nellore Urban": [
  ],
  "Nellore Rural": [],
  "Indukurpet": [],
  "T.P. Gudur": [],
  "Muthukur": [],
  "Venkatachalam": [],
  "Podalakur": [],
  "Rapur": [],
  "Kovur": [],
  "Buchireddypalem": [],
  "Manubolu": [],
  "Sydapuram": [],
  "Atmakur": [],
  "Kaluvoya": [],
  "Chejerla": [],
  "Ananthasagaram": [],
  "A.S. Peta": [],
  "Sangam": [],
  "S.R. Puram": [],
  "Udayagiri": [],
  "Marripadu": [],
  "Kavali": [],
  "Allur": [],
  "Kodavalur": [],
  "Vidavalur": [],
  "Vinjamur": [],
  "Dagadarthi": [],
  "Bogole": [],
  "Jaladanki": [],
  "Duttalur": [],
  "Kaligiri": [],
  "Gudur": [],
  "Sullurpeta": [],
  "Naidupeta": [],
  "Venkatagiri": [],
  "Tada": [],
  "Chittamur": [],
  "Vakadu": [],
  "Kondapuram": [],
  "Dakkili": [],
  "Doravarisatram": [],
  "Ojili": [],
  "Pellakur": [],
  "Balayapalle": [],
  "Varikuntapadu": []
};
